GET http://localhost:8000/api/playlists/groups/124103193

###

POST http://localhost:8000/api/playlists/groups
Content-Type: application/json

{
    "spotifyId": "1Osl5Wo118qBElD9r5U8Ui",
    "userId": "124103193"
}
###

DELETE http://localhost:8000/api/playlists/groups/2WWyPOenj3RpJqftv7WcQ1

###

GET http://localhost:8000/api/playlists/auth/refresh?refresh_token=AQBI8BR6sua_5bOrjVpRKXBsHNawQItjTDgb4_ni7_pnEUBf1phVaolSRyOOfEZsF_83o0nOSDhf_3gXpLsI4rsGxrqM3IJ6_YQwka2v4GpZ7HWpnc-Pb8Fx-8LX2dma6UM



